on:
  issues:
    types: [labeled]

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.labeled }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
